mysite/myauth/urls.py
from django.urls import path
from .models import User
from .views import (
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    # AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    ProfileUpdateView,
    ProfileDetailView,
    HelloWorldView,
    AboutMeView,
)
from django.contrib.auth.views import LoginView


app_name = 'myauth'

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("logaut/", MyLogoutView.as_view(), name="logaut"),
    path("users-list/about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("foo-bar", FooBarView.as_view(), name="foo-bar"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("profile/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("hello/", HelloWorldView.as_view(), name="hello")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView,\
    SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page

from .views import (
    ShopIndexView,
    GroupListView,
    OrderListView,
    ProductCreateView,
    # create_order,
    ProductDetailsView,
    ProductListView,
    OrderDetailsView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductFeed,
    UserOrdersListView,
    UserOrdersExportView,
)


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    # path("orders/create/", create_order, name="order_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("api/", include(routers.urls)),
    path("products/latest/feed/", LatestProductFeed(), name="product_feed"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="users_orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersExportView.as_view(), name="users_orders_export"),
]

mysite/shopapp/forms.py
from django import forms
from .models import Product, Order
from django.forms import ModelForm
from django.contrib.auth.models import Group


# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(label="Product Description",
#                                   widget=forms.Textarea(attrs={"rows": 5}))

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"allow_multiple_selected": True}), required=False
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "user", "products", "promocode"


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
В это модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""
from django.contrib.syndication.views import Feed
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, \
    JsonResponse
from django.contrib.auth.models import Group, User
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from rest_framework import serializers
from django.core import serializers
from .forms import ProductForm, GroupForm
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, \
    UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin, UserPassesTestMixin
from .models import Product, Order, ProductImage
from rest_framework.viewsets import ModelViewSet
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema
import logging
from csv import DictReader, DictWriter
from rest_framework.decorators import action
from rest_framework.request import Request
from django.contrib.sitemaps import Sitemap
from django.utils.decorators import method_decorator


log = logging.getLogger(__name__)


class UserOrdersListView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_authenticated

    @method_decorator(cache_page(60 * 15))
    def get(self, request, user_id):
        self.owner = get_object_or_404(User, id=user_id)
        orders = Order.objects.filter(user=self.owner)
        context = {
            'user': self.owner,
            'orders': orders,
        }
        return render(request, 'shopapp/users_orders_list.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.owner
        return context


class UserOrdersExportView(View):
    def get(self, request: HttpRequest, user_id) -> JsonResponse:
        user = get_object_or_404(User, id=user_id)
        cache_key = f'user_orders_export{user_id}'
        cached_data = cache.get(cache_key)

        if cached_data:
            return JsonResponse(cached_data, safe=False)

        orders = Order.objects.filter(user=user).order_by("id")
        serializer = OrderSerializer(orders, many=True)
        serialized_data = serializer.data

        cache.set(cache_key, serialized_data, 60 * 5)

        return JsonResponse(serialized_data, safe=False)


class LatestProductFeed(Feed):
    title = "Shop products (Latest)"
    description = "Update on change and addition shop products"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return Product.objects.all()

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]

    def item_link(self, item: Product):
        return reverse("shopapp:product_details", kwargs={"pk": item.pk})


class ShopSitemap(Sitemap):
    changefreg = "never"
    priority = 0.5

    def items(self):
        return Product.objects.all()

    def lastmod(self, obj: Product):
        return obj.created_at


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностец товара.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found"
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["user", "products"]
    filterset_fields = [
        "user",
        "products",
        "promocode",
        "delivery_address",
    ]
    ordering_fields = [
        "user",
        "products",
        "promocode",
    ]


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('SmartTV', 2000),
        ]
        context = {
            'products': products,
            'items': 5,
        }
        log.debug("Products for shop index: s%", products)
        log.info("Rendering shop index")
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/product-details.html'
    model = Product
    context_object_name = "product"


class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        instance = form.instance
        instance.created_by = self.request.user
        instance.save()
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    # template_name_suffix = '_update_form'
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrderListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.
        select_related("user").
        prefetch_related("products")
    )


class OrderDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects.
        select_related("user").
        prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "user", "products", "promocode"
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "user", "products", "promocode"
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        return JsonResponse({"products": products_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock title %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock body %}

<div>
    {% now 'H:i' %}
</div>


</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
    </form>
    </div>

    <div>
    <a href="{% url 'shopapp:orders_list' %}"
    >Back to order list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}


{% block body %}
{% if perms.foo %}
    <p>You have permission to do something in the foo app.</p>
    <h1>Create a new product</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
    </form>
    </div>

    <div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
    </div>
{% else %}
    <p>You don't have permission to do anything in the foo app.</p>
{% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Group list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
    <h1>No groups yet!</h1>
    {% else %}
        <ul>
            {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                        <li>
                            {{ permission.name }}
                            (<code>{{ permission.codename }}</code>)
                        </li>
                    {% endfor %}
                </ul>

            </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}


{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}"
    >Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>

         {% if product.preview %}
             <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
         {% endif %}

        <h3>{% translate 'Images' %}:</h3>
        <div>
        {% blocktranslate count images_count=product.images.all|length %}
            {% plural %}
            Upload {{ images_count }} images.
        {% endblocktranslate %}
        </div>
        <div>

            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                    <div>{{ image.description }}</div>
                </div>
            {% empty %}
                <div>{% translate 'No images uploaded yet' %}</div>
            {% endfor %}
        </div>

    </div>
    {% url 'shopapp:product_update' pk=product.pk as product_update_url %}
    {% url 'shopapp:product_delete' pk=product.pk as product_detail_url %}
    {% url 'shopapp:products_list' as products_list_url %}
    {% blocktranslate %}
    <div>
        <a href="{{ product_update_url }}">Update product</a>
    </div>
    <div>
        <a href="{{ product_detail_url }}">Archive product</a>
    </div>
    <div>
        <a href="{{ products_list_url }}">Back to products list</a>
    </div>
    {% endblocktranslate %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}


{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
        </form>
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update _form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block titlt %}
{% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
        {% blocktranslate count product_count=products|length %}
            There is only one product.
            {% plural %}
            There are {{ product_count }} products.
        {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
                <p>{% translate 'Price' %}: {{ product.price }}</p>
                {% translate 'no discount' as no_discount %}
                <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}

            </div>
            {% endfor %}
        </div>

        <div>
        <a href="{% url 'shopapp:product_create' %}"
        >{% translate 'Create a new product' %}</a>
        </div>
    {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
        <h3>No products yet</h3>
        <a href="{{ create_product_url }}"
        >Create a new product</a>
        {% endblocktranslate %}
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Shop Index:</h1>
    <p>
    <a href="{% url 'shopapp:groups_list' %}">Groups</a>
    </p>
    <p>
    <a href="{% url 'shopapp:products_list' %}">Products</a>
    </p>
    <a href="{% url 'shopapp:orders_list' %}">Orders</a>
    </p>
    <div>
        <strong>
            You have {{ items }} item{{ items|pluralize }}
        </strong>
    </div>

    {% cache 100 lorem %}
        <div>
            {% lorem 3 p random %}
        </div>
    {% endcache %}

{% endblock %}

mysite/shopapp/templates/shopapp/users_orders_list.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block titlt %}
    User
{% endblock %}

{% block body %}
    <h1>User {{ user.username }} create next orders:</h1>
    {% cache 100 'orders_'|add:owner.id %}
    <h3>Orders:</h3>
    {% if orders %}
        <div>
            {% for order in orders %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
                >Details #{{ order.pk }}</a> </p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for ${{ product.price }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>

    {% else %}
        <h3>At the user {{ user.username }} no orders yet</h3>
    {% endif %}
    {% endcache %}

{% endblock %}