mysite/myauth/urls.py
from django.urls import path
from .models import User
from .views import (
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    # AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    ProfileUpdateView,
    ProfileDetailView,
    HelloWorldView,
    AboutMeView,
)
from django.contrib.auth.views import LoginView


app_name = 'myauth'

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("logaut/", MyLogoutView.as_view(), name="logaut"),
    path("users-list/about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("foo-bar", FooBarView.as_view(), name="foo-bar"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("profile/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("hello/", HelloWorldView.as_view(), name="hello")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView,\
    SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def user_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "users/user_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=user_avatar_directory_path)

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("user", "bio", "avatar")

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, \
    user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LogoutView
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from .models import Profile
from .forms import ProfileEditForm
from django.utils.translation import gettext_lazy as _, ngettext


class HelloWorldView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}<h1/>"
            f"<h2>{products_line}<h2/>"
        )


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("shopapp:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})


class UsersListView(ListView):
    model = User
    template_name = "myauth/users-list.html"
    context_object_name = "users"


class ProfileUpdateView(UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.request.user.is_staff

    model = Profile
    form_class = ProfileEditForm

    def get_success_url(self):
        return reverse(
            "myauth:about-me",
            kwargs={"pk": self.object.pk},
        )


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "myauth/about-me.html"

mysite/myauth/templates/myauth/about-me.html
{% extends "myauth/base.html" %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Details</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>BIO: {{ user.profile.bio }}</p>
        {% if user.is_authenticated or user.is_staff %}
            <div>
                <a href="{% url 'myauth:profile_update' pk=user.profile.pk %}"
                >Update profile</a>
            </div>
        {% endif %}
        <p>Avatar:
        {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}"></p>
        {% else %}
            <div>No images uploaded yet</div>
        {% endif %}

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}



{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>
    </form>

{% endblock %}

mysite/myauth/templates/myauth/profile_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update profile</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <div>
    <a href="{% url 'myauth:users-list' %}"
    >Back to users list</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update profile</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <div>
    <a href="{% url 'myauth:about-me' pk=user.pk %}"
    >Back to about me #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends "myauth/base.html" %}

{% block titlt %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users:</h1>
    {% if users %}
        <div>
            {% for user in users %}
            <div>
                <a href="{% url 'myauth:profile_detail' pk=user.profile.pk %}"><p>Name: {{ user.username }}</p></a>


                {% if user.profile.avatar %}
                    <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
                {% endif %}

            </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No users yet</h3>
    {% endif %}

{% endblock %}